const allStates = [
  { label: 'Andhra Pradesh', id: 'Andhra Pradesh' },
  { label: 'Arunachal Pradesh', id: 'Arunachal Pradesh' },
  { label: 'Assam', id: 'Assam' },
  { label: 'Bihar', id: 'Bihar' },
  { label: 'Chhattisgarh', id: 'Chhattisgarh' },
  { label: 'Goa', id: 'Goa' },
  { label: 'Gujarat', id: 'Gujarat' },
  { label: 'Haryana', id: 'Haryana' },
  { label: 'Himachal Pradesh', id: 'Himachal Pradesh' },
  { label: 'Jharkhand', id: 'Jharkhand' },
  { label: 'Karnataka', id: 'Karnataka' },
  { label: 'Kerala', id: 'Kerala' },
  { label: 'Madhya Pradesh', id: 'Madhya Pradesh' },
  { label: 'Maharashtra', id: 'Maharashtra' },
  { label: 'Manipur', id: 'Manipur' },
  { label: 'Meghalaya', id: 'Meghalaya' },
  { label: 'Mizoram', id: 'Mizoram' },
  { label: 'Nagaland', id: 'Nagaland' },
  { label: 'Odisha', id: 'Odisha' },
  { label: 'Punjab', id: 'Punjab' },
  { label: 'Rajasthan', id: 'Rajasthan' },
  { label: 'Sikkim', id: 'Sikkim' },
  { label: 'Tamil Nadu', id: 'Tamil Nadu' },
  { label: 'Telangana', id: 'Telangana' },
  { label: 'Tripura', id: 'Tripura' },
  { label: 'Uttar Pradesh', id: 'Uttar Pradesh' },
  { label: 'Uttarakhand', id: 'Uttarakhand' },
  { label: 'West Bengal', id: 'West Bengal' },
];

const ownershipOptions = [
  { label: 'Government', id: 'Government' },
  { label: 'Private', id: 'Private' },
  { label: 'Trust', id: 'Trust' },
  { label: 'NGO', id: 'NGO' },
  { label: 'Corporate', id: 'Corporate' },
  { label: 'Cooperative', id: 'Cooperative' },
];

const doctorSpecializations = [
  { label: 'Cardiology', id: 'Cardiology' },
  { label: 'Neurology', id: 'Neurology' },
  { label: 'Orthopedics', id: 'Orthopedics' },
  { label: 'Pediatrics', id: 'Pediatrics' },
  { label: 'Dermatology', id: 'Dermatology' },
  { label: 'Gynecology', id: 'Gynecology' },
  { label: 'Oncology', id: 'Oncology' },
  { label: 'Psychiatry', id: 'Psychiatry' },
  { label: 'Gastroenterology', id: 'Gastroenterology' },
  { label: 'Ophthalmology', id: 'Ophthalmology' },
  { label: 'Dentistry', id: 'Dentistry' },
  { label: 'Urology', id: 'Urology' },
  { label: 'ENT (Ear, Nose, Throat)', id: 'ENT (Ear, Nose, Throat)' },
  { label: 'Endocrinology', id: 'Endocrinology' },
  { label: 'Rheumatology', id: 'Rheumatology' },
  { label: 'Nephrology', id: 'Nephrology' },
  { label: 'Pulmonology', id: 'Pulmonology' },
  { label: 'Hematology', id: 'Hematology' },
  { label: 'Plastic Surgery', id: 'Plastic Surgery' },
  { label: 'Emergency Medicine', id: 'Emergency Medicine' },
];

export { allStates, ownershipOptions, doctorSpecializations };
